# Generated by Django 3.2 on 2021-04-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'verbose_name_plural': 'Web Site Info'},
        ),
        migrations.RenameField(
            model_name='website',
            old_name='facebok_link',
            new_name='facebook_link',
        ),
    ]
